/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qurocityquiz;

import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Insets;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileReader;
import java.util.Scanner;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;


/**
 *
 * @author ACER
 */
public class questionPresentation extends javax.swing.JFrame {

    /**
     * Creates new form questionPresentation
     */
     public static int no=0;
    JLabel my_label;
    private int col=0;
    String gt;
    private String op[];
    public static int result[] = new int[11];
    public questionPresentation(String p, String o[]) {
        
        initComponents();
        
        myImage(p);
        op=o;
        repaint1();
        jTextField1.setBorder(new RoundedBorder(15));
         jTextField2.setBorder(new RoundedBorder(15));
         jTextField3.setBorder(new RoundedBorder(15));
         jTextField4.setBorder(new RoundedBorder(15));
        
        setLocation(350,10);
        setTitle("Curosity Quiz");
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 225, Short.MAX_VALUE)
        );

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Calibri", 2, 18)); // NOI18N
        jLabel6.setText("                  CUROSITY QUIZ");
        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(0, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 0)));
        jPanel3.setMinimumSize(new java.awt.Dimension(630, 217));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Next One");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField3.setText("jTextField3");
        jTextField3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 255, 0)));
        jTextField3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField3.setMinimumSize(new java.awt.Dimension(55, 16));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField3MouseExited(evt);
            }
        });

        jTextField4.setText("jTextField4");
        jTextField4.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(51, 255, 0)));
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField4.setMinimumSize(new java.awt.Dimension(55, 16));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField4MouseExited(evt);
            }
        });

        jTextField1.setText("jTextField1");
        jTextField1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 0)));
        jTextField1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField1.setMinimumSize(new java.awt.Dimension(55, 16));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField1MouseExited(evt);
            }
        });

        jTextField2.setText("j");
        jTextField2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 0)));
        jTextField2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTextField2.setMinimumSize(new java.awt.Dimension(55, 16));
        jTextField2.setPreferredSize(new java.awt.Dimension(55, 16));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTextField2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextField2MouseExited(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Repaint");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(92, 92, 92))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 659, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 133, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
       
        
        repaint1();
           
           
        
    }//GEN-LAST:event_jButton2ActionPerformed
    void repaint1()
    {
        col=0;
        gt="";
        if(op.length>=1)
        {jTextField1.setText(op[0]); jTextField1.setVisible(!false);
        }else 
            jTextField1.setVisible(false);
        if(op.length>=2)
        {jTextField2.setText(op[1]);  jTextField2.setVisible(!false);}
        else 
            jTextField2.setVisible(false);
        if(op.length>=3)
        {jTextField3.setText(op[2]); jTextField3.setVisible(!false);}
        else 
            jTextField3.setVisible(false);
        if(op.length>=4)
        {jTextField4.setText(op[3]); jTextField4.setVisible(!false);}
        else 
            jTextField4.setVisible(false);
       
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        
        jTextField1.setBackground(Color.lightGray);
         jTextField2.setBackground(Color.lightGray);
          jTextField3.setBackground(Color.lightGray);
           jTextField4.setBackground(Color.lightGray);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(gt.length()<1)
        {JOptionPane.showMessageDialog(null,"  Please Chosse any Felid "," Empty Option ",
                        JOptionPane.ERROR_MESSAGE);
                        return;
        }
        checkresult();
        setVisible(false);
        questionPresentation.no++;
        questionPresentation.genrateQuestion();
        return;
    }//GEN-LAST:event_jButton1ActionPerformed
    void checkresult()
    {
       
        if(no==1&&col==1)
        {
           questionPresentation. result[7]++;
            questionPresentation.result[6]+=1;
            System.out.println(result[7]);
        }
        else if(no==1&&col==2)
                {
                 questionPresentation.result[0]+=1;
                 questionPresentation.result[1]+=1;
                 questionPresentation.result[4]+=1;
                }
        else if(no==1&&col==3)
                {
                 questionPresentation.result[6]+=1;
                 questionPresentation.result[10]+=1;
                }
        else if(no==1&&col==4)
                {
                 questionPresentation.result[0]++;
                 questionPresentation.result[1]+=1;
                 questionPresentation.result[2]+=1;
                 questionPresentation.result[3]+=1;
                }
        else if(no==2&&col==1)
                {
                
                }
         else if(no==2&&col==2)
                {
                
                }
          else if(no==2&&col==3)
                {
                 questionPresentation.result[5]+=1;
                 questionPresentation.result[7]+=1;
                 questionPresentation.result[8]+=1;
                }
        else if(no==2&&col==4)
                {
                 questionPresentation.result[4]+=1;
                 questionPresentation.result[6]+=1;
                 questionPresentation.result[9]+=1;
                 questionPresentation.result[10]+=1;
                }
        else if(no==3&&col==1)
                {
                 questionPresentation.result[0]+=1;
                 questionPresentation.result[1]+=1;
                 questionPresentation.result[2]+=1;
                 questionPresentation.result[3]+=1;
                 questionPresentation.result[9]+=1;
                 questionPresentation.result[5]+=1;
                }
         else if(no==3&&col==2)
                {
                questionPresentation. result[0]+=1;
                 questionPresentation.result[1]+=1;
                 questionPresentation.result[2]+=1;
                 questionPresentation.result[3]+=1;
                questionPresentation. result[4]+=1;
                
                }
        else if(no==3&&col==3)
                {
                questionPresentation. result[7]+=1;
                 questionPresentation.result[8]+=1;
                
                
                }
        else if(no==3&&col==4)
                {
                
                 questionPresentation.result[10]+=1;
                 questionPresentation.result[4]+=1;
                
                }
        else if(no==4&&col==1)
                {
                 questionPresentation.result[9]+=1;
                                
                }
         else if(no==4&&col==2)
                {
                questionPresentation. result[8]+=1;
                questionPresentation. result[4]+=1;
                
                }
         else if(no==4&&col==3)
                {
                
                questionPresentation. result[1]+=1;
                questionPresentation. result[7]+=1;
                
                }
         else if(no==4&&col==4)
                {
                questionPresentation. result[0]+=1;
                questionPresentation. result[3]+=1;
                questionPresentation. result[2]+=1;
               
                }
         else if(no==5&&col==1)
                {
                 questionPresentation.result[0]+=1;
                 questionPresentation.result[1]+=1;
                
                questionPresentation. result[3]+=1;
                questionPresentation. result[5]+=1;
                questionPresentation. result[7]+=1;
                questionPresentation. result[9]+=1;
                
                }
        else if(no==5&&col==2)
                {
                questionPresentation. result[4]+=1;
                }
       
        else if(no==6&&col==1)
                {
                 questionPresentation.result[6]+=1;
                 questionPresentation.result[10]+=1;
                }
        else if(no==6&&col==2)
                {
                
                }
         else if(no==7&&col==1)
                {
                 questionPresentation. result[6]+=1;
                 questionPresentation.  result[10]+=1;
                }
         else if(no==7&&col==2)
                {
                 
                }
        else if(no==7&&col==3)
                {
                 
                }
        else if(no==8&&col==1)
                {
                 questionPresentation. result[4]+=1;
                 questionPresentation. result[5]+=1;
                }
        else if(no==8&&col==2)
                {
                 questionPresentation. result[7]+=1;
                
                }
         else if(no==9&&col==1)
                {
                 questionPresentation. result[10]+=1;
                
                }
        else if(no==9&&col==2)
                {
                questionPresentation.  result[4]+=1;
                
                }
        else if(no==9&&col==3)
                {
                questionPresentation.  result[0]+=1;
                 questionPresentation. result[1]+=1;
                 questionPresentation. result[3]+=1;
                
                }
        else if(no==9&&col==4)
                {
                 questionPresentation. result[2]+=1;
                 
                
                }
        else if(no==10&&col==1)
                {
                 questionPresentation. result[0]+=1;
                 questionPresentation. result[1]+=1;
                 questionPresentation. result[2]+=1;
                 questionPresentation. result[3]+=1;
                }
        else if(no==10&&col==2)
                {
                 questionPresentation. result[4]+=1;
                 questionPresentation. result[8]+=1;
                 
                }
        else if(no==10&&col==3)
                {
                questionPresentation.  result[6]+=1;
                
                 
                }
         else if(no==10&&col==4)
                {
                
                }
         else if(no==11&&col==1)
                {
                 questionPresentation. result[5]+=1;
                 
                
                }
        else if(no==11&&col==2)
                {
                questionPresentation.  result[9]+=1;
                 
                
                }
        else if(no==11&&col==3)
                {
                
                }
        else if(no==11&&col==4)
                {
               questionPresentation.   result[6]+=1;
                questionPresentation.  result[7]+=1;
                questionPresentation. result[10]+=1;
                }
        else if(no==12&&col==1)
                {
                 questionPresentation. result[0]+=1;
                 questionPresentation. result[2]+=1;
                
                }
         else if(no==12&&col==2)
                {
                 questionPresentation. result[1]+=1;
                 
                
                }
        else if(no==12&&col==3)
                {
                 questionPresentation. result[9]+=1;
                 questionPresentation. result[5]+=1;
                
                }
        else if(no==12&&col==4)
                {
                 questionPresentation. result[4]+=1;
                 
                
                }
        else if(no==13&&col==1)
                {
                 questionPresentation. result[4]+=1;
                 
                
                }
        else if(no==13&&col==2)
                {
                
                }
        else if(no==13&&col==3)
                {
                
                
                }
        else if(no==13&&col==4)
                {
                 questionPresentation. result[9]+=1;
                
                }
        else if(no==14&&col==1)
                {
                 questionPresentation. result[4]+=1;
                questionPresentation.  result[6]+=1;
                questionPresentation.  result[7]+=1;
                 questionPresentation.  result[8]+=1;
                 questionPresentation.   result[10]+=1;
                }
        else if(no==14&&col==2)
                {
                 questionPresentation. result[5]+=1;
                 
                }
        else if(no==15&&col==1)
                {
                 questionPresentation. result[0]+=1;
                 questionPresentation. result[1]+=1;
                 questionPresentation. result[3]+=1;
                 
                }
         else if(no==15&&col==2)
                {
                 
                 
                         }
         else if(no==15&&col==2)
                {
                 
                 
                         } 
         else if(no==15&&col==3)
                {
                 
                 questionPresentation. result[2]+=1;
                 questionPresentation. result[5]+=1;
                         }
        else if(no==16&&col==1)
                {
                 
                questionPresentation.  result[1]+=1;
                questionPresentation.  result[5]+=1;
                 questionPresentation. result[9]+=1;
                         }
         else if(no==16&&col==2)
                {
                 
                  questionPresentation.result[0]+=1;
                 questionPresentation. result[2]+=1;
                 
                         }
         else if(no==17&&col==1)
                {
                 
                 questionPresentation. result[0]+=1;
                questionPresentation.  result[4]+=1;
                 questionPresentation. result[9]+=1;
                         }
         else if(no==17&&col==2)
                {
                 
                  questionPresentation.result[3]+=1;
                
                         }
         else if(no==17&&col==3)
                {
                 
                  questionPresentation.result[1]+=1;
                 questionPresentation.  result[7]+=1;
                  questionPresentation.result[9]+=1;
                         }
        else if(no==17&&col==4)
                {
                 
                 questionPresentation. result[5]+=1;
                  
                         }
          else if(no==18&&col==1)
                {
                 
                 questionPresentation. result[0]+=1;
                 questionPresentation. result[1]+=1;
                 questionPresentation. result[10]+=1;
                  
                         }
        else if(no==18&&col==2)
                {
                 
                
                         }
        else if(no==18&&col==3)
                {
                 
                
                  
                         }
        else if(no==18&&col==4)
                {
                         }
        else if(no==19&&col==1)
                {
                 
                 questionPresentation. result[4]+=1;
                 questionPresentation. result[5]+=1;
                 questionPresentation. result[10]+=1;
                  
                         }
         else if(no==19&&col==2)
                {
                         }
         else if(no==20&&col==1)
                {
                 
                  questionPresentation.result[4]+=1;
                  questionPresentation.result[6]+=1;
                 
                  
                         }
         else if(no==20&&col==2)
                {
                 
                         }
         else if(no==21&&col==1)
                {
                 
                  questionPresentation.result[1]+=1;
                
                  
                         }
         else if(no==21&&col==2)
                {
                 
                 
                  
                         }
        else if(no==22&&col==1)
                {
                 
                 questionPresentation. result[4]+=1;
                 questionPresentation.result[10]+=1;
                  
                         }
        else if(no==22&&col==2)
                {
                 
                  
                         }
        else if(no==23&&col==1)
                {
                 
                 questionPresentation. result[4]+=1;
                 questionPresentation.result[8]+=1;
                  
                         }
        else if(no==23&&col==2)
                {
                 
                  questionPresentation.result[7]+=1;

                         }
        
        
        
        
        
        
        
        
    }
    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField1.setBackground(Color.red);
        jTextField1.setEditable(false);
        col=1;
        gt=jTextField1.getText();
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jTextField1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseEntered
        // TODO add your handling code here:
        jTextField1.setEditable(!false);
        jTextField1.setForeground(Color.green);
        jTextField1.setFont( new Font("",Font.BOLD | Font.ITALIC,15));
        if(col==0)
        jTextField1.setBackground(Color.white);
    }//GEN-LAST:event_jTextField1MouseEntered

    private void jTextField1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseExited
        // TODO add your handling code here:
        jTextField1.setEditable(false);
         jTextField1.setForeground(Color.black);
         if(col==0)
         jTextField1.setBackground(Color.lightGray);
        jTextField1.setFont( new Font("",Font.BOLD | Font.ITALIC,11));
    }//GEN-LAST:event_jTextField1MouseExited

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        jTextField1.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setVisible(false);
        jTextField2.setBackground(Color.red);
        jTextField2.setEditable(false);
        col=2;
         gt=jTextField2.getText();
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseEntered
        // TODO add your handling code here:
        jTextField2.setEditable(!false);
        jTextField2.setForeground(Color.green);
        if(col==0)
         jTextField2.setBackground(Color.white);
        jTextField2.setFont( new Font("",Font.BOLD | Font.ITALIC,15));
    }//GEN-LAST:event_jTextField2MouseEntered

    private void jTextField2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseExited
        // TODO add your handling code here:
         jTextField2.setEditable(false);
         jTextField2.setForeground(Color.black);
         if(col==0)
          jTextField2.setBackground(Color.lightGray);
            jTextField2.setFont( new Font("",Font.BOLD | Font.ITALIC,11));
    }//GEN-LAST:event_jTextField2MouseExited

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField4.setVisible(false);
        jTextField3.setBackground(Color.red);
        jTextField3.setEditable(false);
        col=3;
         gt=jTextField3.getText();
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseEntered
        // TODO add your handling code here:
         jTextField3.setEditable(!false);
        jTextField3.setForeground(Color.green);
                 if(col==0)
         jTextField3.setBackground(Color.white);

        jTextField3.setFont( new Font("",Font.BOLD | Font.ITALIC,15));
    }//GEN-LAST:event_jTextField3MouseEntered

    private void jTextField3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseExited
        // TODO add your handling code here:
         jTextField3.setEditable(false);
         jTextField3.setForeground(Color.black);
         if(col==0)
          jTextField3.setBackground(Color.lightGray);
            jTextField3.setFont( new Font("",Font.BOLD | Font.ITALIC,11));
            
    }//GEN-LAST:event_jTextField3MouseExited

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
        jTextField1.setVisible(false);
        jTextField2.setVisible(false);
        jTextField3.setVisible(false);
        jTextField4.setBackground(Color.red);
        jTextField4.setEditable(false);
        col=4;
         gt=jTextField4.getText();
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseEntered
        // TODO add your handling code here:
        jTextField4.setEditable(!false);
        jTextField4.setForeground(Color.green);
        if(col==0)
         jTextField4.setBackground(Color.white);
        jTextField4.setFont( new Font("",Font.BOLD | Font.ITALIC,15));
    }//GEN-LAST:event_jTextField4MouseEntered

    private void jTextField4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseExited
        // TODO add your handling code here:
         jTextField4.setEditable(false);
         jTextField4.setForeground(Color.black);
         if(col==0)
          jTextField4.setBackground(Color.lightGray);
            jTextField4.setFont( new Font("",Font.BOLD | Font.ITALIC,11));
    }//GEN-LAST:event_jTextField4MouseExited

    /**
     * @param args the command line arguments  Career
     */
    void myImage(String x)
    {
        try {
            String path = x;
            File file = new File(path);
            BufferedImage image = ImageIO.read(file);
            my_label = new JLabel(new ImageIcon(image));
            my_label.setLocation(0,0);
            my_label.setSize(650,225);
            jPanel2.add(my_label);}
        catch ( Exception e){
            System.err.println(e);
        }
        
        try {
            String path = "Career.jpg";
            File file = new File(path);
            BufferedImage image = ImageIO.read(file);
            JLabel L = new JLabel(new ImageIcon(image));
            L.setLocation(0,0);
            L.setSize(660,175);
            jPanel4.add(L);}
        catch ( Exception e){
            System.err.println(e);
        }
        
        
    }
    
    
   public static void genrateQuestion()
    {
       
            
            File f = new File("q"+Integer.toString(no)+".jpg");
          //  System.out.println("i cam"+no);
           if( f.exists()==true)
           {
               String ans[]= readData("a"+Integer.toString(no)+".txt");
               new questionPresentation("q"+Integer.toString(no)+".jpg",ans).setVisible(true);
               
           }
           else
           {
              new resultDisplay(result).setVisible(true);
               
           }
        
    }
     private static  String[] readData(String n)
    {
        String a[]={};
        try{
        Scanner sc = new Scanner(new  FileReader(n));
        a= sc.nextLine().split("_");
        
        sc.close();
        }
        catch(Exception e)
        {
            
        }
       
       return a;
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(questionPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(questionPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(questionPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(questionPresentation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new questionPresentation().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
class RoundedBorder implements Border {
        int radius;
        RoundedBorder(int radius) {
            this.radius = radius;
        }
        public Insets getBorderInsets(Component c) {
            return new Insets(this.radius+1, this.radius+1, this.radius+2, this.radius);
        }
        public boolean isBorderOpaque() {
            return true;
        }
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            g.drawRoundRect(x,y,width-1,height-1,radius,radius);
        }
    }